"""Emit OrcaSlicer-format G-code for known geometry, so the parser has
something with an analytically checkable answer.

Mimics real Orca output: relative E (M83), ;TYPE: feature comments,
;LAYER_CHANGE + ;Z: markers, and a trailing CONFIG_BLOCK.
"""
import math, os, sys

OUT = os.path.dirname(os.path.abspath(__file__))
FIL_D = 1.75
FIL_A = math.pi * (FIL_D/2)**2

class G:
    def __init__(self):
        self.L = []
        self.x = self.y = 0.0
    def c(self, s): self.L.append("; " + s)
    def raw(self, s): self.L.append(s)
    def travel(self, x, y):
        self.L.append(f"G1 X{x:.3f} Y{y:.3f} F9000")
        self.x, self.y = x, y
    def extrude(self, x, y, w, h):
        L = math.hypot(x-self.x, y-self.y)
        if L < 1e-9: return
        vol = L * w * h                      # mm^3 of plastic laid down
        e = vol / FIL_A                      # mm of filament (relative E)
        self.L.append(f"G1 X{x:.3f} Y{y:.3f} E{e:.5f} F1800")
        self.x, self.y = x, y

def rect_loop(g, x0, y0, x1, y1, w, h):
    g.travel(x0, y0)
    for (px, py) in ((x1,y0),(x1,y1),(x0,y1),(x0,y0)):
        g.extrude(px, py, w, h)

def solid_square(path, size=20.0, height=10.0, lh=0.2, ew=0.45, walls=2,
                 infill=1.0, pattern="rectilinear"):
    g = G()
    g.c("generated by OrcaSlicer 2.1.1 on 2026-09-22")
    g.raw("M83"); g.raw("G90"); g.raw("G92 E0")
    nl = int(round(height/lh))
    cx = cy = 30.0
    for li in range(nl):
        z = (li+1)*lh
        g.raw(";LAYER_CHANGE")
        g.raw(f";Z:{z:.2f}")
        g.raw(f";LAYER:{li}")
        g.raw(f"G1 Z{z:.2f} F600")
        x0, y0 = cx-size/2, cy-size/2
        x1, y1 = cx+size/2, cy+size/2
        # walls, inset by half a bead each time
        for wi in range(walls):
            g.raw(";TYPE:" + ("Outer wall" if wi==0 else "Inner wall"))
            o = ew*(0.5 + wi)
            rect_loop(g, x0+o, y0+o, x1-o, y1-o, ew, lh)
        # interior
        inner = size - 2*walls*ew
        if inner > ew:
            ix0, iy0 = cx-inner/2, cy-inner/2
            g.raw(";TYPE:" + ("Internal solid infill" if infill>=0.999 else "Sparse infill"))
            spacing = ew/infill
            n = int(inner/spacing)
            if n > 0:
                step = inner/n
                yy = iy0 + step/2
                flip = False
                for k in range(n):
                    if yy > iy0+inner: break
                    if flip:
                        g.travel(ix0+inner, yy); g.extrude(ix0, yy, ew, lh)
                    else:
                        g.travel(ix0, yy); g.extrude(ix0+inner, yy, ew, lh)
                    flip = not flip
                    yy += step
    g.raw("; CONFIG_BLOCK_START")
    for k, v in [("filament_type","PLA"),("layer_height",f"{lh}"),
                 ("wall_loops",f"{walls}"),
                 ("sparse_infill_density",f"{infill*100:.0f}%"),
                 ("sparse_infill_pattern",pattern),
                 ("nozzle_diameter","0.4"),("filament_diameter","1.75"),
                 ("use_relative_e_distances","1")]:
        g.raw(f"; {k} = {v}")
    g.raw("; CONFIG_BLOCK_END")
    open(path,"w").write("\n".join(g.L)+"\n")
    return dict(size=size, height=height, lh=lh, ew=ew, walls=walls, infill=infill)

if __name__ == "__main__":
    m = solid_square(os.path.join(OUT,"solid20.gcode"), infill=1.0)
    print("solid20.gcode", m)
    m = solid_square(os.path.join(OUT,"sparse20.gcode"), infill=0.15)
    print("sparse20.gcode", m)
    m = solid_square(os.path.join(OUT,"tall.gcode"), size=15, height=40, infill=0.25)
    print("tall.gcode", m)


def plate_with_hole(path, W=20.0, L=40.0, height=4.0, hole_d=6.0,
                    lh=0.2, ew=0.45, walls=2):
    """A flat bar with a circular hole through it.

    d/W = 6/20 = 0.3, so Peterson's net-section fit gives Kt = 2.35 — a
    number the detector can be checked against.
    """
    g = G()
    g.c("generated by OrcaSlicer 2.1.1 on 2026-09-23")
    g.raw("M83"); g.raw("G90"); g.raw("G92 E0")
    cx, cy = 50.0, 50.0
    x0, y0 = cx - L/2, cy - W/2
    hx, hy, hr = cx, cy, hole_d/2
    nl = int(round(height/lh))
    for li in range(nl):
        z = (li+1)*lh
        g.raw(";LAYER_CHANGE"); g.raw(f";Z:{z:.2f}"); g.raw(f";LAYER:{li}")
        g.raw(f"G1 Z{z:.2f} F600")
        for wi in range(walls):
            o = ew*(0.5 + wi)
            # outer contour, counter-clockwise
            g.raw(";TYPE:" + ("Outer wall" if wi == 0 else "Inner wall"))
            rect_loop(g, x0+o, y0+o, x0+L-o, y0+W-o, ew, lh)
            # the hole, wound the other way, as slicers emit them
            r = hr + o
            g.travel(hx + r, hy)
            n = 48
            for k in range(1, n+1):
                a = -2*math.pi*k/n
                g.extrude(hx + r*math.cos(a), hy + r*math.sin(a), ew, lh)
        # rectilinear fill, skipping the hole
        g.raw(";TYPE:Sparse infill")
        inner = W - 2*walls*ew
        n = max(1, int(inner/(ew/0.4)))
        for k in range(n):
            yy = y0 + walls*ew + inner*(k+0.5)/n
            ax, bx = x0 + walls*ew, x0 + L - walls*ew
            dy = abs(yy - hy)
            if dy < hr + walls*ew:
                dx = math.sqrt(max((hr + walls*ew)**2 - dy*dy, 0))
                g.travel(ax, yy); g.extrude(hx - dx, yy, ew, lh)
                g.travel(hx + dx, yy); g.extrude(bx, yy, ew, lh)
            else:
                g.travel(ax, yy); g.extrude(bx, yy, ew, lh)
    g.raw("; CONFIG_BLOCK_START")
    for k, v in [("filament_type","PLA"),("layer_height",f"{lh}"),
                 ("wall_loops",f"{walls}"),("sparse_infill_density","40%"),
                 ("sparse_infill_pattern","rectilinear"),("nozzle_diameter","0.4"),
                 ("filament_diameter","1.75")]:
        g.raw(f"; {k} = {v}")
    g.raw("; CONFIG_BLOCK_END")
    open(path,"w").write("\n".join(g.L)+"\n")


def notched_plate(path, W=20.0, L=40.0, height=4.0, notch_d=5.0, notch_r=1.0,
                  lh=0.2, ew=0.45, walls=2):
    """A bar with a semicircular notch cut into one edge, root radius 1 mm."""
    g = G()
    g.c("generated by OrcaSlicer 2.1.1 on 2026-09-23")
    g.raw("M83"); g.raw("G90"); g.raw("G92 E0")
    cx, cy = 50.0, 50.0
    x0, y0 = cx - L/2, cy - W/2
    nl = int(round(height/lh))
    for li in range(nl):
        z = (li+1)*lh
        g.raw(";LAYER_CHANGE"); g.raw(f";Z:{z:.2f}"); g.raw(f";LAYER:{li}")
        g.raw(f"G1 Z{z:.2f} F600")
        for wi in range(walls):
            o = ew*(0.5 + wi)
            g.raw(";TYPE:" + ("Outer wall" if wi == 0 else "Inner wall"))
            ax, ay = x0+o, y0+o
            bx, by = x0+L-o, y0+W-o
            r = notch_r
            g.travel(ax, ay)
            g.extrude(bx, ay, ew, lh)
            g.extrude(bx, by, ew, lh)
            # top edge, interrupted by the notch
            g.extrude(cx + r, by, ew, lh)
            n = 24
            for k in range(1, n+1):
                a = 0 + math.pi*k/n
                g.extrude(cx + r*math.cos(a), by - r*math.sin(a), ew, lh)
            g.extrude(ax, by, ew, lh)
            g.extrude(ax, ay, ew, lh)
        g.raw(";TYPE:Sparse infill")
        inner = W - 2*walls*ew
        n = max(1, int(inner/(ew/0.4)))
        for k in range(n):
            yy = y0 + walls*ew + inner*(k+0.5)/n
            g.travel(x0+walls*ew, yy); g.extrude(x0+L-walls*ew, yy, ew, lh)
    g.raw("; CONFIG_BLOCK_START")
    for k, v in [("filament_type","PLA"),("layer_height",f"{lh}"),
                 ("wall_loops",f"{walls}"),("sparse_infill_density","40%"),
                 ("nozzle_diameter","0.4"),("filament_diameter","1.75")]:
        g.raw(f"; {k} = {v}")
    g.raw("; CONFIG_BLOCK_END")
    open(path,"w").write("\n".join(g.L)+"\n")
