/* Example geometry, generated rather than shipped.
 *
 * Emits OrcaSlicer-format G-code for the same L-bracket in two orientations,
 * so the page opens on a real analysis and the orientation comparison works
 * with nothing loaded. Same geometry as tests/make_gcode.py, written here to
 * keep 280 KB of fixture text out of the page.
 */
const SAMPLES = (() => {
  const FIL_A = Math.PI * Math.pow(1.75/2, 2);
  const EW = 0.45, LH = 0.2;

  function emit(footprint, height, walls, infill) {
    const L = ["; generated by OrcaSlicer 2.1.1 (example geometry)", "M83", "G90", "G92 E0"];
    let cx = 0, cy = 0;
    const move = (x, y) => { L.push(`G1 X${x.toFixed(3)} Y${y.toFixed(3)} F9000`); cx = x; cy = y; };
    const ext = (x, y, w) => {
      const ln = Math.hypot(x - cx, y - cy);
      if (ln < 1e-9) return;
      L.push(`G1 X${x.toFixed(3)} Y${y.toFixed(3)} E${(ln*w*LH/FIL_A).toFixed(5)} F1800`);
      cx = x; cy = y;
    };
    const nl = Math.round(height/LH);
    for (let li = 0; li < nl; li++) {
      const z = (li+1)*LH;
      L.push(";LAYER_CHANGE", `;Z:${z.toFixed(2)}`, `;LAYER:${li}`, `G1 Z${z.toFixed(2)} F600`);
      for (const [x0, y0, x1, y1] of footprint(z)) {
        for (let wi = 0; wi < walls; wi++) {
          L.push(";TYPE:" + (wi === 0 ? "Outer wall" : "Inner wall"));
          const o = EW*(0.5 + wi);
          const a = x0+o, b = y0+o, c = x1-o, d = y1-o;
          if (c <= a || d <= b) break;
          move(a, b); ext(c, b, EW); ext(c, d, EW); ext(a, d, EW); ext(a, b, EW);
        }
        const ix0 = x0 + walls*EW, iy0 = y0 + walls*EW;
        const ix1 = x1 - walls*EW, iy1 = y1 - walls*EW;
        if (ix1 - ix0 > EW && iy1 - iy0 > EW) {
          L.push(";TYPE:Sparse infill");
          const span = iy1 - iy0, sp = EW/infill;
          const n = Math.max(1, Math.floor(span/sp));
          for (let k = 0; k < n; k++) {
            const yy = iy0 + span*(k + 0.5)/n;
            move(ix0, yy); ext(ix1, yy, EW);
          }
        }
      }
    }
    L.push("; CONFIG_BLOCK_START", "; filament_type = PLA", "; layer_height = 0.2",
           `; wall_loops = ${walls}`, `; sparse_infill_density = ${(infill*100).toFixed(0)}%`,
           "; sparse_infill_pattern = grid", "; nozzle_diameter = 0.4",
           "; filament_diameter = 1.75", "; CONFIG_BLOCK_END");
    return L.join("\n") + "\n";
  }

  // The L lies in the print plane, 4 mm tall.
  const flat = () => emit(() => [[0,0,40,20], [0,20,20,40]], 4.0, 3, 0.20);
  // The same L stood up: one leg is now built vertically, layer on layer.
  const upright = () => emit(z => z <= 4.0 ? [[0,0,40,20]] : [[0,0,4,20]], 40.0, 3, 0.20);

  // A bar with a hole through it: d/W = 0.3, so the textbook net-section
  // factor is Kt = 2.35 and the detector has something to find.
  function plateWithHole() {
    const W = 20, L = 40, height = 4, hr = 3, walls = 2;
    const Lz = [], x0 = 0, y0 = 0, hx = L/2, hy = W/2;
    let cx = 0, cy = 0;
    const move = (x,y) => { Lz.push(`G1 X${x.toFixed(3)} Y${y.toFixed(3)} F9000`); cx=x; cy=y; };
    const ext = (x,y,w) => {
      const ln = Math.hypot(x-cx, y-cy);
      if (ln < 1e-9) return;
      Lz.push(`G1 X${x.toFixed(3)} Y${y.toFixed(3)} E${(ln*w*LH/FIL_A).toFixed(5)} F1800`);
      cx=x; cy=y;
    };
    Lz.push("; generated by OrcaSlicer 2.1.1 (example geometry)", "M83", "G90", "G92 E0");
    for (let li = 0; li < Math.round(height/LH); li++) {
      const z = (li+1)*LH;
      Lz.push(";LAYER_CHANGE", `;Z:${z.toFixed(2)}`, `;LAYER:${li}`, `G1 Z${z.toFixed(2)} F600`);
      for (let wi = 0; wi < walls; wi++) {
        const o = EW*(0.5+wi);
        Lz.push(";TYPE:" + (wi === 0 ? "Outer wall" : "Inner wall"));
        move(x0+o, y0+o);
        ext(x0+L-o, y0+o, EW); ext(x0+L-o, y0+W-o, EW);
        ext(x0+o, y0+W-o, EW); ext(x0+o, y0+o, EW);
        const r = hr + o;
        move(hx + r, hy);
        for (let k = 1; k <= 48; k++) {
          const a = -2*Math.PI*k/48;
          ext(hx + r*Math.cos(a), hy + r*Math.sin(a), EW);
        }
      }
      Lz.push(";TYPE:Sparse infill");
      const inner = W - 2*walls*EW, n = Math.max(1, Math.floor(inner/(EW/0.4)));
      for (let k = 0; k < n; k++) {
        const yy = y0 + walls*EW + inner*(k+0.5)/n;
        const ax = x0 + walls*EW, bx = x0 + L - walls*EW;
        const dy = Math.abs(yy - hy), rr = hr + walls*EW;
        if (dy < rr) {
          const dx = Math.sqrt(Math.max(rr*rr - dy*dy, 0));
          move(ax, yy); ext(hx-dx, yy, EW);
          move(hx+dx, yy); ext(bx, yy, EW);
        } else { move(ax, yy); ext(bx, yy, EW); }
      }
    }
    Lz.push("; CONFIG_BLOCK_START", "; filament_type = PLA", "; layer_height = 0.2",
            `; wall_loops = ${walls}`, "; sparse_infill_density = 40%",
            "; nozzle_diameter = 0.4", "; filament_diameter = 1.75", "; CONFIG_BLOCK_END");
    return Lz.join("\n") + "\n";
  }

  return {
    "bracket — printed flat":    {name:"bracket-flat.gcode",    make: flat},
    "bracket — printed upright": {name:"bracket-upright.gcode", make: upright},
    "bar with a hole":           {name:"bar-with-hole.gcode",   make: plateWithHole},
  };
})();
if (typeof module !== "undefined") module.exports = SAMPLES;
